import aiopubsub
from src.widgets.widget.widget import Widget as BaseWidget
import asyncio
from aiohttp import ClientSession
import logging

logger = logging.getLogger(__name__)

api_key = "985503aa43e84b6395f193425220103"


class Widget(BaseWidget):
    widget_name = "WEATHER"
    worker_is_needed = False

    async def _start_instance(self):
        try:
            required_args = [
                "data-refresh-interval",
                "data-location",
                "data-days",
            ]
            missing_args = [arg for arg in required_args if arg not in self._kwargs]
            if missing_args:
                msg = {"msg": f"Missing attributes: {missing_args}"}
                logger.warning(msg)
                await self._render_widget_html_and_send_to_queue(msg)
                await asyncio.sleep(0)
                return

            location = self._kwargs["data-location"]
            days = self._kwargs["data-days"]

            refresh_interval = self._kwargs["data-refresh-interval"]

            client = ClientSession()

            # Start the loop
            current_i = 0
            while True:
                logger.info("Calling weather API")
                response = await client.get(
                    url=f"http://api.weatherapi.com/v1/forecast.json?key={api_key}&q={location}&days={days}&aqi=no&alerts=no"
                )
                result = await response.json()
                logger.info(f"request_url={response.url}")
                logger.info(f"response={result}")

                context = result
                # DO SOMETHING

                ###################################
                await self._render_widget_html_and_send_to_queue(context)
                ###################################
                await asyncio.sleep(int(refresh_interval))
        except asyncio.CancelledError:
            pass
            # CLEAN UP


"""
{
  "location": {
    "name": "Ealing",
    "region": "London",
    "country": "UK",
    "lat": 51.51,
    "lon": -0.3,
    "tz_id": "Europe/London",
    "localtime_epoch": 1646168443,
    "localtime": "2022-03-01 21:00"
  },
  "current": {
    "last_updated_epoch": 1646164800,
    "last_updated": "2022-03-01 20:00",
    "temp_c": 7.0,
    "temp_f": 44.6,
    "is_day": 0,
    "condition": {
      "text": "Light rain",
      "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
      "code": 1183
    },
    "wind_mph": 9.4,
    "wind_kph": 15.1,
    "wind_degree": 70,
    "wind_dir": "ENE",
    "pressure_mb": 1025.0,
    "pressure_in": 30.27,
    "precip_mm": 0.8,
    "precip_in": 0.03,
    "humidity": 93,
    "cloud": 100,
    "feelslike_c": 4.2,
    "feelslike_f": 39.5,
    "vis_km": 8.0,
    "vis_miles": 4.0,
    "uv": 1.0,
    "gust_mph": 14.3,
    "gust_kph": 23.0
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2022-03-01",
        "date_epoch": 1646092800,
        "day": {
          "maxtemp_c": 8.0,
          "maxtemp_f": 46.4,
          "mintemp_c": 7.0,
          "mintemp_f": 44.6,
          "avgtemp_c": 7.8,
          "avgtemp_f": 46.1,
          "maxwind_mph": 10.7,
          "maxwind_kph": 17.3,
          "totalprecip_mm": 23.7,
          "totalprecip_in": 0.93,
          "avgvis_km": 7.6,
          "avgvis_miles": 4.0,
          "avghumidity": 94.0,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 99,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Heavy rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/308.png",
            "code": 1195
          },
          "uv": 1.0
        },
        "astro": {
          "sunrise": "06:47 AM",
          "sunset": "05:42 PM",
          "moonrise": "06:52 AM",
          "moonset": "03:55 PM",
          "moon_phase": "Waning Crescent",
          "moon_illumination": "2"
        },
        "hour": [
          {
            "time_epoch": 1646092800,
            "time": "2022-03-01 00:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
              "code": 1189
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 202,
            "wind_dir": "SSW",
            "pressure_mb": 1024.0,
            "pressure_in": 30.23,
            "precip_mm": 2.5,
            "precip_in": 0.1,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 7.7,
            "feelslike_f": 45.9,
            "windchill_c": 7.7,
            "windchill_f": 45.9,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 8.5,
            "dewpoint_f": 47.3,
            "will_it_rain": 1,
            "chance_of_rain": 98,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 7.0,
            "vis_miles": 4.0,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 1.0
          },
          {
            "time_epoch": 1646096400,
            "time": "2022-03-01 01:00",
            "temp_c": 9.2,
            "temp_f": 48.6,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 196,
            "wind_dir": "SSW",
            "pressure_mb": 1024.0,
            "pressure_in": 30.23,
            "precip_mm": 1.0,
            "precip_in": 0.04,
            "humidity": 96,
            "cloud": 100,
            "feelslike_c": 8.1,
            "feelslike_f": 46.6,
            "windchill_c": 8.1,
            "windchill_f": 46.6,
            "heatindex_c": 9.2,
            "heatindex_f": 48.6,
            "dewpoint_c": 8.6,
            "dewpoint_f": 47.5,
            "will_it_rain": 1,
            "chance_of_rain": 98,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 7.6,
            "gust_kph": 12.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1646100000,
            "time": "2022-03-01 02:00",
            "temp_c": 9.0,
            "temp_f": 48.2,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 169,
            "wind_dir": "S",
            "pressure_mb": 1024.0,
            "pressure_in": 30.23,
            "precip_mm": 0.9,
            "precip_in": 0.04,
            "humidity": 97,
            "cloud": 100,
            "feelslike_c": 8.4,
            "feelslike_f": 47.1,
            "windchill_c": 8.4,
            "windchill_f": 47.1,
            "heatindex_c": 9.0,
            "heatindex_f": 48.2,
            "dewpoint_c": 8.6,
            "dewpoint_f": 47.5,
            "will_it_rain": 1,
            "chance_of_rain": 97,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 5.6,
            "gust_kph": 9.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646103600,
            "time": "2022-03-01 03:00",
            "temp_c": 8.7,
            "temp_f": 47.7,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 1.1,
            "wind_kph": 1.8,
            "wind_degree": 50,
            "wind_dir": "NE",
            "pressure_mb": 1024.0,
            "pressure_in": 30.24,
            "precip_mm": 2.4,
            "precip_in": 0.09,
            "humidity": 98,
            "cloud": 100,
            "feelslike_c": 8.7,
            "feelslike_f": 47.7,
            "windchill_c": 8.7,
            "windchill_f": 47.7,
            "heatindex_c": 8.7,
            "heatindex_f": 47.7,
            "dewpoint_c": 8.4,
            "dewpoint_f": 47.1,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 1.8,
            "gust_kph": 2.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1646107200,
            "time": "2022-03-01 04:00",
            "temp_c": 8.6,
            "temp_f": 47.5,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 12,
            "wind_dir": "NNE",
            "pressure_mb": 1024.0,
            "pressure_in": 30.25,
            "precip_mm": 0.9,
            "precip_in": 0.04,
            "humidity": 98,
            "cloud": 100,
            "feelslike_c": 7.8,
            "feelslike_f": 46.0,
            "windchill_c": 7.8,
            "windchill_f": 46.0,
            "heatindex_c": 8.6,
            "heatindex_f": 47.5,
            "dewpoint_c": 8.3,
            "dewpoint_f": 46.9,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1646110800,
            "time": "2022-03-01 05:00",
            "temp_c": 8.3,
            "temp_f": 46.9,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 25,
            "wind_dir": "NNE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.27,
            "precip_mm": 1.0,
            "precip_in": 0.04,
            "humidity": 96,
            "cloud": 100,
            "feelslike_c": 6.0,
            "feelslike_f": 42.8,
            "windchill_c": 6.0,
            "windchill_f": 42.8,
            "heatindex_c": 8.3,
            "heatindex_f": 46.9,
            "dewpoint_c": 7.7,
            "dewpoint_f": 45.9,
            "will_it_rain": 1,
            "chance_of_rain": 98,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 13.0,
            "gust_kph": 20.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1646114400,
            "time": "2022-03-01 06:00",
            "temp_c": 8.0,
            "temp_f": 46.4,
            "is_day": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
              "code": 1189
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 31,
            "wind_dir": "NNE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.27,
            "precip_mm": 5.2,
            "precip_in": 0.2,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 5.3,
            "feelslike_f": 41.5,
            "windchill_c": 5.3,
            "windchill_f": 41.5,
            "heatindex_c": 8.0,
            "heatindex_f": 46.4,
            "dewpoint_c": 7.0,
            "dewpoint_f": 44.6,
            "will_it_rain": 1,
            "chance_of_rain": 88,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 7.0,
            "vis_miles": 4.0,
            "gust_mph": 14.5,
            "gust_kph": 23.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1646118000,
            "time": "2022-03-01 07:00",
            "temp_c": 7.8,
            "temp_f": 46.0,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 30,
            "wind_dir": "NNE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.28,
            "precip_mm": 0.2,
            "precip_in": 0.01,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 5.1,
            "feelslike_f": 41.2,
            "windchill_c": 5.1,
            "windchill_f": 41.2,
            "heatindex_c": 7.8,
            "heatindex_f": 46.0,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 14.8,
            "gust_kph": 23.8,
            "uv": 2.0
          },
          {
            "time_epoch": 1646121600,
            "time": "2022-03-01 08:00",
            "temp_c": 7.8,
            "temp_f": 46.0,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 34,
            "wind_dir": "NE",
            "pressure_mb": 1026.0,
            "pressure_in": 30.29,
            "precip_mm": 0.3,
            "precip_in": 0.01,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 4.9,
            "feelslike_f": 40.8,
            "windchill_c": 4.9,
            "windchill_f": 40.8,
            "heatindex_c": 7.8,
            "heatindex_f": 46.0,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 1,
            "chance_of_rain": 97,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 15.7,
            "gust_kph": 25.2,
            "uv": 2.0
          },
          {
            "time_epoch": 1646125200,
            "time": "2022-03-01 09:00",
            "temp_c": 7.7,
            "temp_f": 45.9,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 36,
            "wind_dir": "NE",
            "pressure_mb": 1026.0,
            "pressure_in": 30.3,
            "precip_mm": 0.5,
            "precip_in": 0.02,
            "humidity": 92,
            "cloud": 100,
            "feelslike_c": 4.9,
            "feelslike_f": 40.8,
            "windchill_c": 4.9,
            "windchill_f": 40.8,
            "heatindex_c": 7.7,
            "heatindex_f": 45.9,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 1,
            "chance_of_rain": 99,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 14.5,
            "gust_kph": 23.4,
            "uv": 2.0
          },
          {
            "time_epoch": 1646128800,
            "time": "2022-03-01 10:00",
            "temp_c": 7.6,
            "temp_f": 45.7,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 41,
            "wind_dir": "NE",
            "pressure_mb": 1027.0,
            "pressure_in": 30.32,
            "precip_mm": 0.1,
            "precip_in": 0.0,
            "humidity": 91,
            "cloud": 100,
            "feelslike_c": 4.8,
            "feelslike_f": 40.6,
            "windchill_c": 4.8,
            "windchill_f": 40.6,
            "heatindex_c": 7.6,
            "heatindex_f": 45.7,
            "dewpoint_c": 6.3,
            "dewpoint_f": 43.3,
            "will_it_rain": 0,
            "chance_of_rain": 54,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.1,
            "gust_kph": 22.7,
            "uv": 2.0
          },
          {
            "time_epoch": 1646132400,
            "time": "2022-03-01 11:00",
            "temp_c": 7.6,
            "temp_f": 45.7,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 43,
            "wind_dir": "NE",
            "pressure_mb": 1027.0,
            "pressure_in": 30.32,
            "precip_mm": 0.1,
            "precip_in": 0.0,
            "humidity": 91,
            "cloud": 100,
            "feelslike_c": 4.8,
            "feelslike_f": 40.6,
            "windchill_c": 4.8,
            "windchill_f": 40.6,
            "heatindex_c": 7.6,
            "heatindex_f": 45.7,
            "dewpoint_c": 6.2,
            "dewpoint_f": 43.2,
            "will_it_rain": 1,
            "chance_of_rain": 80,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.6,
            "gust_kph": 22.0,
            "uv": 2.0
          },
          {
            "time_epoch": 1646136000,
            "time": "2022-03-01 12:00",
            "temp_c": 7.6,
            "temp_f": 45.7,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 46,
            "wind_dir": "NE",
            "pressure_mb": 1027.0,
            "pressure_in": 30.32,
            "precip_mm": 0.6,
            "precip_in": 0.02,
            "humidity": 91,
            "cloud": 100,
            "feelslike_c": 4.8,
            "feelslike_f": 40.6,
            "windchill_c": 4.8,
            "windchill_f": 40.6,
            "heatindex_c": 7.6,
            "heatindex_f": 45.7,
            "dewpoint_c": 6.2,
            "dewpoint_f": 43.2,
            "will_it_rain": 0,
            "chance_of_rain": 69,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 13.2,
            "gust_kph": 21.2,
            "uv": 2.0
          },
          {
            "time_epoch": 1646139600,
            "time": "2022-03-01 13:00",
            "temp_c": 7.6,
            "temp_f": 45.7,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 46,
            "wind_dir": "NE",
            "pressure_mb": 1026.0,
            "pressure_in": 30.31,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 91,
            "cloud": 100,
            "feelslike_c": 4.9,
            "feelslike_f": 40.8,
            "windchill_c": 4.9,
            "windchill_f": 40.8,
            "heatindex_c": 7.6,
            "heatindex_f": 45.7,
            "dewpoint_c": 6.2,
            "dewpoint_f": 43.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.0,
            "gust_kph": 20.9,
            "uv": 2.0
          },
          {
            "time_epoch": 1646143200,
            "time": "2022-03-01 14:00",
            "temp_c": 7.5,
            "temp_f": 45.5,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 52,
            "wind_dir": "NE",
            "pressure_mb": 1026.0,
            "pressure_in": 30.3,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 91,
            "cloud": 100,
            "feelslike_c": 4.8,
            "feelslike_f": 40.6,
            "windchill_c": 4.8,
            "windchill_f": 40.6,
            "heatindex_c": 7.5,
            "heatindex_f": 45.5,
            "dewpoint_c": 6.2,
            "dewpoint_f": 43.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 2.0
          },
          {
            "time_epoch": 1646146800,
            "time": "2022-03-01 15:00",
            "temp_c": 7.5,
            "temp_f": 45.5,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 53,
            "wind_dir": "NE",
            "pressure_mb": 1026.0,
            "pressure_in": 30.28,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 92,
            "cloud": 100,
            "feelslike_c": 4.7,
            "feelslike_f": 40.5,
            "windchill_c": 4.7,
            "windchill_f": 40.5,
            "heatindex_c": 7.5,
            "heatindex_f": 45.5,
            "dewpoint_c": 6.3,
            "dewpoint_f": 43.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.1,
            "gust_kph": 22.7,
            "uv": 2.0
          },
          {
            "time_epoch": 1646150400,
            "time": "2022-03-01 16:00",
            "temp_c": 7.6,
            "temp_f": 45.7,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 59,
            "wind_dir": "ENE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.27,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 92,
            "cloud": 100,
            "feelslike_c": 4.8,
            "feelslike_f": 40.6,
            "windchill_c": 4.8,
            "windchill_f": 40.6,
            "heatindex_c": 7.6,
            "heatindex_f": 45.7,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 14.3,
            "gust_kph": 23.0,
            "uv": 2.0
          },
          {
            "time_epoch": 1646154000,
            "time": "2022-03-01 17:00",
            "temp_c": 7.5,
            "temp_f": 45.5,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 63,
            "wind_dir": "ENE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.27,
            "precip_mm": 0.2,
            "precip_in": 0.01,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 4.8,
            "feelslike_f": 40.6,
            "windchill_c": 4.8,
            "windchill_f": 40.6,
            "heatindex_c": 7.5,
            "heatindex_f": 45.5,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 1,
            "chance_of_rain": 78,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 13.6,
            "gust_kph": 22.0,
            "uv": 2.0
          },
          {
            "time_epoch": 1646157600,
            "time": "2022-03-01 18:00",
            "temp_c": 7.3,
            "temp_f": 45.1,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 72,
            "wind_dir": "ENE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.27,
            "precip_mm": 2.0,
            "precip_in": 0.08,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 4.6,
            "feelslike_f": 40.3,
            "windchill_c": 4.6,
            "windchill_f": 40.3,
            "heatindex_c": 7.3,
            "heatindex_f": 45.1,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 1,
            "chance_of_rain": 83,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1646161200,
            "time": "2022-03-01 19:00",
            "temp_c": 7.2,
            "temp_f": 45.0,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 73,
            "wind_dir": "ENE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.27,
            "precip_mm": 0.9,
            "precip_in": 0.04,
            "humidity": 95,
            "cloud": 100,
            "feelslike_c": 4.5,
            "feelslike_f": 40.1,
            "windchill_c": 4.5,
            "windchill_f": 40.1,
            "heatindex_c": 7.2,
            "heatindex_f": 45.0,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.5,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 13.6,
            "gust_kph": 22.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646164800,
            "time": "2022-03-01 20:00",
            "temp_c": 7.1,
            "temp_f": 44.8,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 70,
            "wind_dir": "ENE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.26,
            "precip_mm": 0.8,
            "precip_in": 0.03,
            "humidity": 95,
            "cloud": 100,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 7.1,
            "heatindex_f": 44.8,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.5,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 14.3,
            "gust_kph": 23.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646168400,
            "time": "2022-03-01 21:00",
            "temp_c": 7.0,
            "temp_f": 44.6,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 71,
            "wind_dir": "ENE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.26,
            "precip_mm": 2.4,
            "precip_in": 0.09,
            "humidity": 96,
            "cloud": 100,
            "feelslike_c": 4.2,
            "feelslike_f": 39.6,
            "windchill_c": 4.2,
            "windchill_f": 39.6,
            "heatindex_c": 7.0,
            "heatindex_f": 44.6,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.5,
            "will_it_rain": 1,
            "chance_of_rain": 90,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 14.1,
            "gust_kph": 22.7,
            "uv": 1.0
          },
          {
            "time_epoch": 1646172000,
            "time": "2022-03-01 22:00",
            "temp_c": 7.0,
            "temp_f": 44.6,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 74,
            "wind_dir": "ENE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.26,
            "precip_mm": 0.8,
            "precip_in": 0.03,
            "humidity": 96,
            "cloud": 100,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 7.0,
            "heatindex_f": 44.6,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 1,
            "chance_of_rain": 89,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1646175600,
            "time": "2022-03-01 23:00",
            "temp_c": 7.1,
            "temp_f": 44.8,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 83,
            "wind_dir": "E",
            "pressure_mb": 1024.0,
            "pressure_in": 30.24,
            "precip_mm": 0.9,
            "precip_in": 0.04,
            "humidity": 97,
            "cloud": 100,
            "feelslike_c": 4.7,
            "feelslike_f": 40.5,
            "windchill_c": 4.7,
            "windchill_f": 40.5,
            "heatindex_c": 7.1,
            "heatindex_f": 44.8,
            "dewpoint_c": 6.6,
            "dewpoint_f": 43.9,
            "will_it_rain": 1,
            "chance_of_rain": 89,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 1.0
          }
        ]
      },
      {
        "date": "2022-03-02",
        "date_epoch": 1646179200,
        "day": {
          "maxtemp_c": 6.8,
          "maxtemp_f": 44.2,
          "mintemp_c": 6.1,
          "mintemp_f": 43.0,
          "avgtemp_c": 6.5,
          "avgtemp_f": 43.7,
          "maxwind_mph": 8.1,
          "maxwind_kph": 13.0,
          "totalprecip_mm": 16.3,
          "totalprecip_in": 0.64,
          "avgvis_km": 7.0,
          "avgvis_miles": 4.0,
          "avghumidity": 86.0,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 94,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Moderate rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
            "code": 1189
          },
          "uv": 1.0
        },
        "astro": {
          "sunrise": "06:44 AM",
          "sunset": "05:43 PM",
          "moonrise": "07:13 AM",
          "moonset": "05:20 PM",
          "moon_phase": "New Moon",
          "moon_illumination": "0"
        },
        "hour": [
          {
            "time_epoch": 1646179200,
            "time": "2022-03-02 00:00",
            "temp_c": 7.0,
            "temp_f": 44.6,
            "is_day": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
              "code": 1189
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 93,
            "wind_dir": "E",
            "pressure_mb": 1024.0,
            "pressure_in": 30.23,
            "precip_mm": 5.1,
            "precip_in": 0.2,
            "humidity": 96,
            "cloud": 100,
            "feelslike_c": 4.7,
            "feelslike_f": 40.5,
            "windchill_c": 4.7,
            "windchill_f": 40.5,
            "heatindex_c": 7.0,
            "heatindex_f": 44.6,
            "dewpoint_c": 6.3,
            "dewpoint_f": 43.3,
            "will_it_rain": 1,
            "chance_of_rain": 94,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 7.0,
            "vis_miles": 4.0,
            "gust_mph": 11.2,
            "gust_kph": 18.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646182800,
            "time": "2022-03-02 01:00",
            "temp_c": 6.8,
            "temp_f": 44.2,
            "is_day": 0,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "code": 1153
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 98,
            "wind_dir": "E",
            "pressure_mb": 1023.0,
            "pressure_in": 30.22,
            "precip_mm": 0.5,
            "precip_in": 0.02,
            "humidity": 93,
            "cloud": 100,
            "feelslike_c": 4.4,
            "feelslike_f": 39.9,
            "windchill_c": 4.4,
            "windchill_f": 39.9,
            "heatindex_c": 6.8,
            "heatindex_f": 44.2,
            "dewpoint_c": 5.8,
            "dewpoint_f": 42.4,
            "will_it_rain": 1,
            "chance_of_rain": 94,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 11.2,
            "gust_kph": 18.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646186400,
            "time": "2022-03-02 02:00",
            "temp_c": 6.5,
            "temp_f": 43.7,
            "is_day": 0,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "code": 1153
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 94,
            "wind_dir": "E",
            "pressure_mb": 1023.0,
            "pressure_in": 30.21,
            "precip_mm": 0.5,
            "precip_in": 0.02,
            "humidity": 93,
            "cloud": 100,
            "feelslike_c": 4.0,
            "feelslike_f": 39.2,
            "windchill_c": 4.0,
            "windchill_f": 39.2,
            "heatindex_c": 6.5,
            "heatindex_f": 43.7,
            "dewpoint_c": 5.4,
            "dewpoint_f": 41.7,
            "will_it_rain": 1,
            "chance_of_rain": 93,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 11.2,
            "gust_kph": 18.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646190000,
            "time": "2022-03-02 03:00",
            "temp_c": 6.3,
            "temp_f": 43.3,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 92,
            "wind_dir": "E",
            "pressure_mb": 1023.0,
            "pressure_in": 30.19,
            "precip_mm": 1.3,
            "precip_in": 0.05,
            "humidity": 92,
            "cloud": 100,
            "feelslike_c": 3.7,
            "feelslike_f": 38.7,
            "windchill_c": 3.7,
            "windchill_f": 38.7,
            "heatindex_c": 6.3,
            "heatindex_f": 43.3,
            "dewpoint_c": 5.2,
            "dewpoint_f": 41.4,
            "will_it_rain": 1,
            "chance_of_rain": 93,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 11.4,
            "gust_kph": 18.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1646193600,
            "time": "2022-03-02 04:00",
            "temp_c": 6.1,
            "temp_f": 43.0,
            "is_day": 0,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "code": 1153
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 94,
            "wind_dir": "E",
            "pressure_mb": 1022.0,
            "pressure_in": 30.19,
            "precip_mm": 0.5,
            "precip_in": 0.02,
            "humidity": 93,
            "cloud": 100,
            "feelslike_c": 3.5,
            "feelslike_f": 38.3,
            "windchill_c": 3.5,
            "windchill_f": 38.3,
            "heatindex_c": 6.1,
            "heatindex_f": 43.0,
            "dewpoint_c": 5.0,
            "dewpoint_f": 41.0,
            "will_it_rain": 1,
            "chance_of_rain": 92,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 1.0
          },
          {
            "time_epoch": 1646197200,
            "time": "2022-03-02 05:00",
            "temp_c": 6.1,
            "temp_f": 43.0,
            "is_day": 0,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "code": 1153
            },
            "wind_mph": 8.1,
            "wind_kph": 13.0,
            "wind_degree": 99,
            "wind_dir": "E",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.6,
            "precip_in": 0.02,
            "humidity": 93,
            "cloud": 100,
            "feelslike_c": 3.4,
            "feelslike_f": 38.1,
            "windchill_c": 3.4,
            "windchill_f": 38.1,
            "heatindex_c": 6.1,
            "heatindex_f": 43.0,
            "dewpoint_c": 5.1,
            "dewpoint_f": 41.2,
            "will_it_rain": 1,
            "chance_of_rain": 92,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 1.0
          },
          {
            "time_epoch": 1646200800,
            "time": "2022-03-02 06:00",
            "temp_c": 6.1,
            "temp_f": 43.0,
            "is_day": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
              "code": 1189
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 106,
            "wind_dir": "ESE",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 3.5,
            "precip_in": 0.14,
            "humidity": 93,
            "cloud": 100,
            "feelslike_c": 3.5,
            "feelslike_f": 38.3,
            "windchill_c": 3.5,
            "windchill_f": 38.3,
            "heatindex_c": 6.1,
            "heatindex_f": 43.0,
            "dewpoint_c": 5.1,
            "dewpoint_f": 41.2,
            "will_it_rain": 1,
            "chance_of_rain": 92,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 7.0,
            "vis_miles": 4.0,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 1.0
          },
          {
            "time_epoch": 1646204400,
            "time": "2022-03-02 07:00",
            "temp_c": 6.2,
            "temp_f": 43.2,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 8.1,
            "wind_kph": 13.0,
            "wind_degree": 109,
            "wind_dir": "ESE",
            "pressure_mb": 1022.0,
            "pressure_in": 30.17,
            "precip_mm": 0.5,
            "precip_in": 0.02,
            "humidity": 93,
            "cloud": 100,
            "feelslike_c": 3.5,
            "feelslike_f": 38.3,
            "windchill_c": 3.5,
            "windchill_f": 38.3,
            "heatindex_c": 6.2,
            "heatindex_f": 43.2,
            "dewpoint_c": 5.1,
            "dewpoint_f": 41.2,
            "will_it_rain": 1,
            "chance_of_rain": 91,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 11.9,
            "gust_kph": 19.1,
            "uv": 2.0
          },
          {
            "time_epoch": 1646208000,
            "time": "2022-03-02 08:00",
            "temp_c": 6.2,
            "temp_f": 43.2,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 8.1,
            "wind_kph": 13.0,
            "wind_degree": 111,
            "wind_dir": "ESE",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.4,
            "precip_in": 0.02,
            "humidity": 92,
            "cloud": 100,
            "feelslike_c": 3.5,
            "feelslike_f": 38.3,
            "windchill_c": 3.5,
            "windchill_f": 38.3,
            "heatindex_c": 6.2,
            "heatindex_f": 43.2,
            "dewpoint_c": 5.0,
            "dewpoint_f": 41.0,
            "will_it_rain": 1,
            "chance_of_rain": 91,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 2.0
          },
          {
            "time_epoch": 1646211600,
            "time": "2022-03-02 09:00",
            "temp_c": 6.4,
            "temp_f": 43.5,
            "is_day": 1,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
              "code": 1183
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 1.0,
            "precip_in": 0.04,
            "humidity": 91,
            "cloud": 100,
            "feelslike_c": 3.8,
            "feelslike_f": 38.8,
            "windchill_c": 3.8,
            "windchill_f": 38.8,
            "heatindex_c": 6.4,
            "heatindex_f": 43.5,
            "dewpoint_c": 5.0,
            "dewpoint_f": 41.0,
            "will_it_rain": 1,
            "chance_of_rain": 91,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 2.0
          },
          {
            "time_epoch": 1646215200,
            "time": "2022-03-02 10:00",
            "temp_c": 6.4,
            "temp_f": 43.5,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.3,
            "precip_in": 0.01,
            "humidity": 89,
            "cloud": 100,
            "feelslike_c": 3.8,
            "feelslike_f": 38.8,
            "windchill_c": 3.8,
            "windchill_f": 38.8,
            "heatindex_c": 6.4,
            "heatindex_f": 43.5,
            "dewpoint_c": 4.8,
            "dewpoint_f": 40.6,
            "will_it_rain": 1,
            "chance_of_rain": 90,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 11.0,
            "gust_kph": 17.6,
            "uv": 2.0
          },
          {
            "time_epoch": 1646218800,
            "time": "2022-03-02 11:00",
            "temp_c": 6.5,
            "temp_f": 43.7,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1022.0,
            "pressure_in": 30.17,
            "precip_mm": 0.3,
            "precip_in": 0.01,
            "humidity": 89,
            "cloud": 100,
            "feelslike_c": 4.0,
            "feelslike_f": 39.2,
            "windchill_c": 4.0,
            "windchill_f": 39.2,
            "heatindex_c": 6.5,
            "heatindex_f": 43.7,
            "dewpoint_c": 4.8,
            "dewpoint_f": 40.6,
            "will_it_rain": 1,
            "chance_of_rain": 90,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 2.0
          },
          {
            "time_epoch": 1646222400,
            "time": "2022-03-02 12:00",
            "temp_c": 6.6,
            "temp_f": 43.9,
            "is_day": 1,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
              "code": 1183
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 110,
            "wind_dir": "ESE",
            "pressure_mb": 1021.0,
            "pressure_in": 30.16,
            "precip_mm": 1.4,
            "precip_in": 0.06,
            "humidity": 88,
            "cloud": 100,
            "feelslike_c": 4.2,
            "feelslike_f": 39.6,
            "windchill_c": 4.2,
            "windchill_f": 39.6,
            "heatindex_c": 6.6,
            "heatindex_f": 43.9,
            "dewpoint_c": 4.8,
            "dewpoint_f": 40.6,
            "will_it_rain": 1,
            "chance_of_rain": 90,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 2.0
          },
          {
            "time_epoch": 1646226000,
            "time": "2022-03-02 13:00",
            "temp_c": 6.8,
            "temp_f": 44.2,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 111,
            "wind_dir": "ESE",
            "pressure_mb": 1021.0,
            "pressure_in": 30.14,
            "precip_mm": 0.1,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 100,
            "feelslike_c": 4.5,
            "feelslike_f": 40.1,
            "windchill_c": 4.5,
            "windchill_f": 40.1,
            "heatindex_c": 6.8,
            "heatindex_f": 44.2,
            "dewpoint_c": 4.7,
            "dewpoint_f": 40.5,
            "will_it_rain": 1,
            "chance_of_rain": 89,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 2.0
          },
          {
            "time_epoch": 1646229600,
            "time": "2022-03-02 14:00",
            "temp_c": 6.7,
            "temp_f": 44.1,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 107,
            "wind_dir": "ESE",
            "pressure_mb": 1020.0,
            "pressure_in": 30.13,
            "precip_mm": 0.1,
            "precip_in": 0.0,
            "humidity": 85,
            "cloud": 100,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 6.7,
            "heatindex_f": 44.1,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.9,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 2.0
          },
          {
            "time_epoch": 1646233200,
            "time": "2022-03-02 15:00",
            "temp_c": 6.7,
            "temp_f": 44.1,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 106,
            "wind_dir": "ESE",
            "pressure_mb": 1020.0,
            "pressure_in": 30.12,
            "precip_mm": 0.1,
            "precip_in": 0.0,
            "humidity": 84,
            "cloud": 100,
            "feelslike_c": 4.5,
            "feelslike_f": 40.1,
            "windchill_c": 4.5,
            "windchill_f": 40.1,
            "heatindex_c": 6.7,
            "heatindex_f": 44.1,
            "dewpoint_c": 4.2,
            "dewpoint_f": 39.6,
            "will_it_rain": 0,
            "chance_of_rain": 53,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 2.0
          },
          {
            "time_epoch": 1646236800,
            "time": "2022-03-02 16:00",
            "temp_c": 6.7,
            "temp_f": 44.1,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 105,
            "wind_dir": "ESE",
            "pressure_mb": 1020.0,
            "pressure_in": 30.11,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 82,
            "cloud": 100,
            "feelslike_c": 4.5,
            "feelslike_f": 40.1,
            "windchill_c": 4.5,
            "windchill_f": 40.1,
            "heatindex_c": 6.7,
            "heatindex_f": 44.1,
            "dewpoint_c": 3.8,
            "dewpoint_f": 38.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 2.0
          },
          {
            "time_epoch": 1646240400,
            "time": "2022-03-02 17:00",
            "temp_c": 6.7,
            "temp_f": 44.1,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 105,
            "wind_dir": "ESE",
            "pressure_mb": 1020.0,
            "pressure_in": 30.11,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 81,
            "cloud": 100,
            "feelslike_c": 4.7,
            "feelslike_f": 40.5,
            "windchill_c": 4.7,
            "windchill_f": 40.5,
            "heatindex_c": 6.7,
            "heatindex_f": 44.1,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.7,
            "gust_kph": 14.0,
            "uv": 2.0
          },
          {
            "time_epoch": 1646244000,
            "time": "2022-03-02 18:00",
            "temp_c": 6.7,
            "temp_f": 44.1,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 104,
            "wind_dir": "ESE",
            "pressure_mb": 1020.0,
            "pressure_in": 30.11,
            "precip_mm": 0.1,
            "precip_in": 0.0,
            "humidity": 79,
            "cloud": 100,
            "feelslike_c": 4.6,
            "feelslike_f": 40.3,
            "windchill_c": 4.6,
            "windchill_f": 40.3,
            "heatindex_c": 6.7,
            "heatindex_f": 44.1,
            "dewpoint_c": 3.3,
            "dewpoint_f": 37.9,
            "will_it_rain": 0,
            "chance_of_rain": 62,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1646247600,
            "time": "2022-03-02 19:00",
            "temp_c": 6.7,
            "temp_f": 44.1,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 110,
            "wind_dir": "ESE",
            "pressure_mb": 1019.0,
            "pressure_in": 30.1,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 77,
            "cloud": 100,
            "feelslike_c": 4.6,
            "feelslike_f": 40.3,
            "windchill_c": 4.6,
            "windchill_f": 40.3,
            "heatindex_c": 6.7,
            "heatindex_f": 44.1,
            "dewpoint_c": 3.0,
            "dewpoint_f": 37.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1646251200,
            "time": "2022-03-02 20:00",
            "temp_c": 6.4,
            "temp_f": 43.5,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 6.0,
            "wind_kph": 9.7,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1019.0,
            "pressure_in": 30.09,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 100,
            "feelslike_c": 4.4,
            "feelslike_f": 39.9,
            "windchill_c": 4.4,
            "windchill_f": 39.9,
            "heatindex_c": 6.4,
            "heatindex_f": 43.5,
            "dewpoint_c": 2.3,
            "dewpoint_f": 36.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1646254800,
            "time": "2022-03-02 21:00",
            "temp_c": 6.5,
            "temp_f": 43.7,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 5.6,
            "wind_kph": 9.0,
            "wind_degree": 113,
            "wind_dir": "ESE",
            "pressure_mb": 1019.0,
            "pressure_in": 30.08,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 74,
            "cloud": 100,
            "feelslike_c": 4.7,
            "feelslike_f": 40.5,
            "windchill_c": 4.7,
            "windchill_f": 40.5,
            "heatindex_c": 6.5,
            "heatindex_f": 43.7,
            "dewpoint_c": 2.3,
            "dewpoint_f": 36.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.7,
            "gust_kph": 14.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646258400,
            "time": "2022-03-02 22:00",
            "temp_c": 6.5,
            "temp_f": 43.7,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 5.6,
            "wind_kph": 9.0,
            "wind_degree": 109,
            "wind_dir": "ESE",
            "pressure_mb": 1018.0,
            "pressure_in": 30.07,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 74,
            "cloud": 100,
            "feelslike_c": 4.7,
            "feelslike_f": 40.5,
            "windchill_c": 4.7,
            "windchill_f": 40.5,
            "heatindex_c": 6.5,
            "heatindex_f": 43.7,
            "dewpoint_c": 2.3,
            "dewpoint_f": 36.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1646262000,
            "time": "2022-03-02 23:00",
            "temp_c": 6.6,
            "temp_f": 43.9,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 109,
            "wind_dir": "ESE",
            "pressure_mb": 1018.0,
            "pressure_in": 30.06,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 74,
            "cloud": 81,
            "feelslike_c": 5.0,
            "feelslike_f": 41.0,
            "windchill_c": 5.0,
            "windchill_f": 41.0,
            "heatindex_c": 6.6,
            "heatindex_f": 43.9,
            "dewpoint_c": 2.4,
            "dewpoint_f": 36.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.1,
            "gust_kph": 13.0,
            "uv": 1.0
          }
        ]
      },
      {
        "date": "2022-03-03",
        "date_epoch": 1646265600,
        "day": {
          "maxtemp_c": 12.1,
          "maxtemp_f": 53.8,
          "mintemp_c": 6.0,
          "mintemp_f": 42.8,
          "avgtemp_c": 8.4,
          "avgtemp_f": 47.1,
          "maxwind_mph": 8.1,
          "maxwind_kph": 13.0,
          "totalprecip_mm": 0.0,
          "totalprecip_in": 0.0,
          "avgvis_km": 10.0,
          "avgvis_miles": 6.0,
          "avghumidity": 72.0,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
          },
          "uv": 2.0
        },
        "astro": {
          "sunrise": "06:42 AM",
          "sunset": "05:45 PM",
          "moonrise": "07:30 AM",
          "moonset": "06:41 PM",
          "moon_phase": "New Moon",
          "moon_illumination": "0"
        },
        "hour": [
          {
            "time_epoch": 1646265600,
            "time": "2022-03-03 00:00",
            "temp_c": 6.3,
            "temp_f": 43.3,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 101,
            "wind_dir": "ESE",
            "pressure_mb": 1017.0,
            "pressure_in": 30.04,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 76,
            "cloud": 97,
            "feelslike_c": 4.6,
            "feelslike_f": 40.3,
            "windchill_c": 4.6,
            "windchill_f": 40.3,
            "heatindex_c": 6.3,
            "heatindex_f": 43.3,
            "dewpoint_c": 2.5,
            "dewpoint_f": 36.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.7,
            "gust_kph": 14.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646269200,
            "time": "2022-03-03 01:00",
            "temp_c": 6.2,
            "temp_f": 43.2,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 107,
            "wind_dir": "ESE",
            "pressure_mb": 1017.0,
            "pressure_in": 30.03,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 78,
            "cloud": 84,
            "feelslike_c": 4.5,
            "feelslike_f": 40.1,
            "windchill_c": 4.5,
            "windchill_f": 40.1,
            "heatindex_c": 6.2,
            "heatindex_f": 43.2,
            "dewpoint_c": 2.6,
            "dewpoint_f": 36.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1646272800,
            "time": "2022-03-03 02:00",
            "temp_c": 6.4,
            "temp_f": 43.5,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 121,
            "wind_dir": "ESE",
            "pressure_mb": 1017.0,
            "pressure_in": 30.02,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 79,
            "cloud": 98,
            "feelslike_c": 5.0,
            "feelslike_f": 41.0,
            "windchill_c": 5.0,
            "windchill_f": 41.0,
            "heatindex_c": 6.4,
            "heatindex_f": 43.5,
            "dewpoint_c": 3.0,
            "dewpoint_f": 37.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1646276400,
            "time": "2022-03-03 03:00",
            "temp_c": 6.5,
            "temp_f": 43.7,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1016.0,
            "pressure_in": 30.01,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 80,
            "cloud": 58,
            "feelslike_c": 4.8,
            "feelslike_f": 40.6,
            "windchill_c": 4.8,
            "windchill_f": 40.6,
            "heatindex_c": 6.5,
            "heatindex_f": 43.7,
            "dewpoint_c": 3.3,
            "dewpoint_f": 37.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1646280000,
            "time": "2022-03-03 04:00",
            "temp_c": 6.5,
            "temp_f": 43.7,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 111,
            "wind_dir": "ESE",
            "pressure_mb": 1016.0,
            "pressure_in": 29.99,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 81,
            "cloud": 66,
            "feelslike_c": 4.9,
            "feelslike_f": 40.8,
            "windchill_c": 4.9,
            "windchill_f": 40.8,
            "heatindex_c": 6.5,
            "heatindex_f": 43.7,
            "dewpoint_c": 3.5,
            "dewpoint_f": 38.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.7,
            "gust_kph": 14.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646283600,
            "time": "2022-03-03 05:00",
            "temp_c": 6.3,
            "temp_f": 43.3,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 105,
            "wind_dir": "ESE",
            "pressure_mb": 1015.0,
            "pressure_in": 29.98,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 82,
            "cloud": 70,
            "feelslike_c": 4.6,
            "feelslike_f": 40.3,
            "windchill_c": 4.6,
            "windchill_f": 40.3,
            "heatindex_c": 6.3,
            "heatindex_f": 43.3,
            "dewpoint_c": 3.5,
            "dewpoint_f": 38.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1646287200,
            "time": "2022-03-03 06:00",
            "temp_c": 6.2,
            "temp_f": 43.2,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 5.6,
            "wind_kph": 9.0,
            "wind_degree": 103,
            "wind_dir": "ESE",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 82,
            "cloud": 56,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 6.2,
            "heatindex_f": 43.2,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1646290800,
            "time": "2022-03-03 07:00",
            "temp_c": 6.0,
            "temp_f": 42.8,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 103,
            "wind_dir": "ESE",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 83,
            "cloud": 66,
            "feelslike_c": 4.0,
            "feelslike_f": 39.2,
            "windchill_c": 4.0,
            "windchill_f": 39.2,
            "heatindex_c": 6.0,
            "heatindex_f": 42.8,
            "dewpoint_c": 3.3,
            "dewpoint_f": 37.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 2.0
          },
          {
            "time_epoch": 1646294400,
            "time": "2022-03-03 08:00",
            "temp_c": 6.5,
            "temp_f": 43.7,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 105,
            "wind_dir": "ESE",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 81,
            "cloud": 33,
            "feelslike_c": 4.4,
            "feelslike_f": 39.9,
            "windchill_c": 4.4,
            "windchill_f": 39.9,
            "heatindex_c": 6.5,
            "heatindex_f": 43.7,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 3.0
          },
          {
            "time_epoch": 1646298000,
            "time": "2022-03-03 09:00",
            "temp_c": 7.6,
            "temp_f": 45.7,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 111,
            "wind_dir": "ESE",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 76,
            "cloud": 46,
            "feelslike_c": 5.5,
            "feelslike_f": 41.9,
            "windchill_c": 5.5,
            "windchill_f": 41.9,
            "heatindex_c": 7.6,
            "heatindex_f": 45.7,
            "dewpoint_c": 3.7,
            "dewpoint_f": 38.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 3.0
          },
          {
            "time_epoch": 1646301600,
            "time": "2022-03-03 10:00",
            "temp_c": 8.9,
            "temp_f": 48.0,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 8.1,
            "wind_kph": 13.0,
            "wind_degree": 124,
            "wind_dir": "SE",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 71,
            "cloud": 83,
            "feelslike_c": 6.8,
            "feelslike_f": 44.2,
            "windchill_c": 6.8,
            "windchill_f": 44.2,
            "heatindex_c": 8.9,
            "heatindex_f": 48.0,
            "dewpoint_c": 3.9,
            "dewpoint_f": 39.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 2.0
          },
          {
            "time_epoch": 1646305200,
            "time": "2022-03-03 11:00",
            "temp_c": 9.7,
            "temp_f": 49.5,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 8.1,
            "wind_kph": 13.0,
            "wind_degree": 127,
            "wind_dir": "SE",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 68,
            "cloud": 97,
            "feelslike_c": 7.8,
            "feelslike_f": 46.0,
            "windchill_c": 7.8,
            "windchill_f": 46.0,
            "heatindex_c": 9.7,
            "heatindex_f": 49.5,
            "dewpoint_c": 4.1,
            "dewpoint_f": 39.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 2.0
          },
          {
            "time_epoch": 1646308800,
            "time": "2022-03-03 12:00",
            "temp_c": 10.2,
            "temp_f": 50.4,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 130,
            "wind_dir": "SE",
            "pressure_mb": 1015.0,
            "pressure_in": 29.96,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 67,
            "cloud": 45,
            "feelslike_c": 8.6,
            "feelslike_f": 47.5,
            "windchill_c": 8.6,
            "windchill_f": 47.5,
            "heatindex_c": 10.2,
            "heatindex_f": 50.4,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 4.0
          },
          {
            "time_epoch": 1646312400,
            "time": "2022-03-03 13:00",
            "temp_c": 10.9,
            "temp_f": 51.6,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 137,
            "wind_dir": "SE",
            "pressure_mb": 1015.0,
            "pressure_in": 29.96,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 64,
            "cloud": 60,
            "feelslike_c": 9.6,
            "feelslike_f": 49.3,
            "windchill_c": 9.6,
            "windchill_f": 49.3,
            "heatindex_c": 10.9,
            "heatindex_f": 51.6,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 4.0
          },
          {
            "time_epoch": 1646316000,
            "time": "2022-03-03 14:00",
            "temp_c": 12.0,
            "temp_f": 53.6,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 134,
            "wind_dir": "SE",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 60,
            "cloud": 57,
            "feelslike_c": 10.9,
            "feelslike_f": 51.6,
            "windchill_c": 10.9,
            "windchill_f": 51.6,
            "heatindex_c": 12.0,
            "heatindex_f": 53.6,
            "dewpoint_c": 4.5,
            "dewpoint_f": 40.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.1,
            "gust_kph": 13.0,
            "uv": 4.0
          },
          {
            "time_epoch": 1646319600,
            "time": "2022-03-03 15:00",
            "temp_c": 12.1,
            "temp_f": 53.8,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 128,
            "wind_dir": "SE",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 59,
            "cloud": 62,
            "feelslike_c": 10.9,
            "feelslike_f": 51.6,
            "windchill_c": 10.9,
            "windchill_f": 51.6,
            "heatindex_c": 12.1,
            "heatindex_f": 53.8,
            "dewpoint_c": 4.3,
            "dewpoint_f": 39.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 4.0
          },
          {
            "time_epoch": 1646323200,
            "time": "2022-03-03 16:00",
            "temp_c": 11.8,
            "temp_f": 53.2,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 121,
            "wind_dir": "ESE",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 60,
            "cloud": 41,
            "feelslike_c": 10.6,
            "feelslike_f": 51.1,
            "windchill_c": 10.6,
            "windchill_f": 51.1,
            "heatindex_c": 11.8,
            "heatindex_f": 53.2,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 4.0
          },
          {
            "time_epoch": 1646326800,
            "time": "2022-03-03 17:00",
            "temp_c": 10.9,
            "temp_f": 51.6,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 117,
            "wind_dir": "ESE",
            "pressure_mb": 1014.0,
            "pressure_in": 29.96,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 64,
            "cloud": 46,
            "feelslike_c": 9.7,
            "feelslike_f": 49.5,
            "windchill_c": 9.7,
            "windchill_f": 49.5,
            "heatindex_c": 10.9,
            "heatindex_f": 51.6,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.7,
            "gust_kph": 14.0,
            "uv": 4.0
          },
          {
            "time_epoch": 1646330400,
            "time": "2022-03-03 18:00",
            "temp_c": 9.8,
            "temp_f": 49.6,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 5.6,
            "wind_kph": 9.0,
            "wind_degree": 108,
            "wind_dir": "ESE",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 70,
            "cloud": 45,
            "feelslike_c": 8.6,
            "feelslike_f": 47.5,
            "windchill_c": 8.6,
            "windchill_f": 47.5,
            "heatindex_c": 9.8,
            "heatindex_f": 49.6,
            "dewpoint_c": 4.5,
            "dewpoint_f": 40.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 1.0
          },
          {
            "time_epoch": 1646334000,
            "time": "2022-03-03 19:00",
            "temp_c": 9.2,
            "temp_f": 48.6,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 96,
            "wind_dir": "E",
            "pressure_mb": 1016.0,
            "pressure_in": 29.99,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 73,
            "cloud": 45,
            "feelslike_c": 8.0,
            "feelslike_f": 46.4,
            "windchill_c": 8.0,
            "windchill_f": 46.4,
            "heatindex_c": 9.2,
            "heatindex_f": 48.6,
            "dewpoint_c": 4.6,
            "dewpoint_f": 40.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.4,
            "gust_kph": 11.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1646337600,
            "time": "2022-03-03 20:00",
            "temp_c": 8.0,
            "temp_f": 46.4,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 84,
            "wind_dir": "E",
            "pressure_mb": 1016.0,
            "pressure_in": 30.01,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 74,
            "cloud": 48,
            "feelslike_c": 6.4,
            "feelslike_f": 43.5,
            "windchill_c": 6.4,
            "windchill_f": 43.5,
            "heatindex_c": 8.0,
            "heatindex_f": 46.4,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1646341200,
            "time": "2022-03-03 21:00",
            "temp_c": 7.7,
            "temp_f": 45.9,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 5.6,
            "wind_kph": 9.0,
            "wind_degree": 80,
            "wind_dir": "E",
            "pressure_mb": 1016.0,
            "pressure_in": 30.01,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 71,
            "cloud": 75,
            "feelslike_c": 6.1,
            "feelslike_f": 43.0,
            "windchill_c": 6.1,
            "windchill_f": 43.0,
            "heatindex_c": 7.7,
            "heatindex_f": 45.9,
            "dewpoint_c": 2.9,
            "dewpoint_f": 37.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.7,
            "gust_kph": 14.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646344800,
            "time": "2022-03-03 22:00",
            "temp_c": 7.9,
            "temp_f": 46.2,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 75,
            "wind_dir": "ENE",
            "pressure_mb": 1017.0,
            "pressure_in": 30.02,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 69,
            "cloud": 87,
            "feelslike_c": 6.4,
            "feelslike_f": 43.5,
            "windchill_c": 6.4,
            "windchill_f": 43.5,
            "heatindex_c": 7.9,
            "heatindex_f": 46.2,
            "dewpoint_c": 2.5,
            "dewpoint_f": 36.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.1,
            "gust_kph": 13.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1646348400,
            "time": "2022-03-03 23:00",
            "temp_c": 7.9,
            "temp_f": 46.2,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 78,
            "wind_dir": "ENE",
            "pressure_mb": 1016.0,
            "pressure_in": 30.01,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 68,
            "cloud": 64,
            "feelslike_c": 6.2,
            "feelslike_f": 43.2,
            "windchill_c": 6.2,
            "windchill_f": 43.2,
            "heatindex_c": 7.9,
            "heatindex_f": 46.2,
            "dewpoint_c": 2.3,
            "dewpoint_f": 36.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 1.0
          }
        ]
      }
    ]
  }
}
"""
